# Generated by Django 6.0.3 on 2026-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_catergory_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[('Drafts', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
