# Generated by Django 6.0.3 on 2026-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_about_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About_heading',
            field=models.CharField(max_length=25),
        ),
    ]
