# Generated by Django 6.0.3 on 2026-03-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_about_about_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='About_description',
            new_name='about_description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='About_heading',
            new_name='about_heading',
        ),
    ]
